name: Ejecución Programada API

on:
  schedule:
    # --- INICIO (Lunes a Viernes) ---
    # 07:00 UTC es 08:00 España
    - cron: '0 7 * * 1-5'

    # --- CIERRE LUNES A JUEVES (8.5 horas después) ---
    # 08:00 + 8.5h = 16:30 España -> 15:30 UTC
    - cron: '30 15 * * 1-4'

    # --- CIERRE VIERNES (6 horas después) ---
    # 08:00 + 6h = 14:00 España -> 13:00 UTC
    - cron: '0 13 * * 5'
  workflow_dispatch: # Permite ejecutarlo manualmente desde GitHub para probar

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Ejecutar script
        run: node index.js
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
